### ISSUE TITLE
Subtitles go wonky when you do the konami code

### ISSUE THREAD

**Issue by andrejsavikin** [AniDevTwitter/animeopenings#170] opened 2016-03-19 20:59 UTC
If you enable subs then do the konami code, the subs will stay behind the video and not rotate. http://s.savikin.me/scr/chrome_2016-03-19_21-57-52.png

**Comment by QuadPiece** [comment] 2016-03-19 21:10
god, this will be horrid to fix

**Comment by andrejsavikin** [comment] 2016-03-19 21:19
You will need to do both rotation and revolution on same subs. Revolution is easy, but good luck with rotation

**Comment by QuadPiece** [comment] 2016-03-19 21:30
Should be too hard honestly to do a basic fix, since they're all in an svg container - The problem is doing it without making performance go to hell and back. If we're gonna bother with that at all.

**Comment by Yay295** [comment] 2016-03-20 20:57
Nah, I got this.

**Comment by QuadPiece** [comment] 2016-03-21 09:58
Fixed by Yay295's patch

**Closed by QuadPiece** 2016-03-21 09:58 UTC
Labels: bug
