### ISSUE TITLE
Subtitles not displaying at all

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#299] opened 2018-07-26 19:16 UTC
I can't quite explain it, but some karaokes don't display at all on my end.

https://lab.shelter.moe/karaokemugen/karaokebase/blob/master/lyrics/JAP%20-%20Mugen%20no%20Ryvius%20-%20OP%20-%20Dis.ass

I thought at first it was the \fad effect but it seems to be supported according to the wiki page (or am I mistaken?)

Is this something I can fix on my end in my .ass file ? Or something you need to implement ?

**Comment by Yay295** [comment] 2018-07-26 21:13
Videos with subtitles should have an icon next to their name in the [video list](http://live.karaokes.moe/list/?s=mugen). Whether or not a video has subtitles is determined by the `subtitles` attribute for the video in your `names.php`. Normally you would put the name of the subtitle creator(s) there, but you can put something else if you don't know who created it. Something has to be there for the site to know it has subtitles though.

**Comment by Yay295** [comment] 2018-07-27 02:48
For the first one, the `subtitles` attribute needs to be set to a *non-empty* string. It basically just does `if (video.subtitles)`, and an empty string is `false`. The second one is caused by a bug in `subtitles.js`.

Also, your ED's for "Aquarian Age: Sign for Evolution" seem to be backwards. The file names at least.

Also also, don't forget to change the rest of the pages to show your own data.

**Comment by AxelTerizaki** [comment] 2018-07-27 18:06
Got it. I rewrote the names.php file to include a string inside each subtitle field.

However, I still have some songs not showing subtitles.

is there some kind of logging enabled to see what's going on?

**Comment by AxelTerizaki** [comment] 2018-07-31 06:48
An example of a song not playing at all : 

ASS : 
https://lab.shelter.moe/karaokemugen/karaokebase/blob/master/lyrics/JAP%20-%20Sin%20Nanatsu%20no%20Taizai%20-%20OP%20-%20My%20Sweet%20Maiden.ass

In names.php the series has a : character. I'll try to see if it's what breaks by replacing it by nothing when generating the file, but I doubt it (

```'Sin: Nanatsu no Taizai' =>
        array (
                'Opening1(jpn)' =>
                array (
                        'file' => 'JAP - Sin Nanatsu no Taizai - OP - My Sweet Maiden',
                        'mime' =>
                        array (
                                0 => 'video/mp4',
                        ),
                        'song' =>
                        array (
                                'title' => 'My Sweet Maiden',
                                'artist' => 'Mia REGINA',
                        ),
                        'subtitles' => 'KuroSensei',
                ),
```

**Comment by AxelTerizaki** [comment] 2018-07-31 06:51
Actually I noticed all the songs after this one did not display subtitles anymore. I had to go again to the base URL to make the browser reload the page.

Since #298 isn't fixed yet I have a hard time retrying specific videos, making it hard to diagnose anything.

**Comment by AxelTerizaki** [comment] 2018-07-31 21:46
Now that #298 is fixed, I was able to confirm that, after a while, subfiles stop appearing. I'll have to keep my eyes on the screen to see when this happens exactly.

- If I skip to another video, subtitles still don't appear
- Hitting F5 reloads the current video and the subtitles display once again. 

I only have Firefox here, but I'll ask friends if they can test with Chrome or Safari

**Comment by Yay295** [comment] 2018-08-06 02:31
Have you noticed yet if there are any specific videos it's not working on?

**Comment by AxelTerizaki** [comment] 2018-08-06 19:29
I can't reply/test for sure this week as I am busy with real life :/

I'll try to give you more info tomorrow, but it wasn't any specific video, really. As I said, it happens after a few videos, and hitting refresh fixes the issue.

I'll try again shortly.

**Comment by AxelTerizaki** [comment] 2018-08-12 20:07
I confirm the issue is still there (I just pulled the latest version). Sometimes when going to a new video subtitles do not appear, reloading fixes things.

I'm running firefox.

**Comment by Yay295** [comment] 2018-08-16 06:17
I've been able to see it a few times now too, but I haven't figured out an exact trigger for it. Just for my own future reference, and to get things written down:

* When getting a new video, the subtitles do not load.
* Checking the network tab shows that the `XMLHttpRequest` for the subtitle file was never sent.
* Upon pausing and playing the video, an error is printed to the console saying that a subtitle line was unable to attach itself to the DOM.
  * This shows that the subtitle event listeners are still active.
  * Checking the subtitle object that encounters the error shows that the previously loaded subtitles are still initialized.
  * The error occurs because the SVG element has been cleared, so the subtitle line cannot find its `<g id="layerN">` to attach to.

So the conclusion is that something is happening between the SVG element being cleared and the subtitles being declared `UNINITIALIZED`, which doesn't make any sense because they happen in the same function.

**Comment by Yay295** [comment] 2018-08-16 06:45
Theory: `renderer.clean();` is called, clearing the SVG element and making it `UNINITIALIZED`. Then the video's `loadedmetadata` callback (`templocal()`) is called, setting it to `INITIALIZED`. This callback doesn't actually initialize anything because it's set to only do things if it's `INITIALIZING`.

**Comment by Yay295** [comment] 2018-08-16 22:50
@AxelTerizaki I can't figure it out, so here's a modified `subtitles.js` with a bunch of `console.log`'s in it: [subtitles.txt](https://github.com/AniDevTwitter/animeopenings/files/2295453/subtitles.txt). GitHub won't let me upload a `.js` file, so you'll have to change the extension. Let me know when that's up and I'll take a look again.

**Comment by AxelTerizaki** [comment] 2018-08-16 23:27
@Yay295 JS is in place o7

**Comment by Yay295** [comment] 2018-08-17 16:44
Thanks. I think I've got it fixed now.

`templocal()` is called on the video's `loadedmetadata` event, but if you get a new video too fast, this event doesn't fire for the video, instead firing for the next video, with the previous video's subtitles still loaded.

**Comment by AxelTerizaki** [comment] 2018-08-25 14:45
I'm not entirely sure this is closed.

I ran into the issue earlier but I still need to reproduce it to make sure, h owever, I ran into a karaoke which doesn't display at all, no matter how much I refresh my browser : 

https://live.karaokes.moe/?video=%20MV%20-JAP%20-%20WORLD%20ORDER%20

Weirdly, if I click on the button to get another video, subs aren't displayed at all on that video either, until I hit F5.

However, for this clip from WORLD ORDER, I don't get any subs no matter how many times I try to F5 my browser.

You can find video and ass files here : http://mugen.karaokes.moe/en/karas/108786d2-3e7a-4a5b-b58f-0b961c6540b7.html

**Comment by AxelTerizaki** [comment] 2018-08-25 20:14
Okay, after some research, we found something interesting.

The ASS I linked references a specific font that does not exist. As a consequence it's never displayed AND seems to break any subsequent ASS file you want to read unless you hit F5.

However, we have another ASS with a non-existant (for AnimeOpenings) font : 

https://live.karaokes.moe/?video=%20Ending%20-JAP%20-%20Momo%20Kyun%20Sword%20

(ASS is here : http://mugen.karaokes.moe/en/karas/8cc096af-7f5c-48ba-9dde-70037af0f840.html)

But strangely this one does play nice and another font is used instead.

So I think the issue is related to whatever subtitles.js does with unknown fonts.

**Comment by AxelTerizaki** [comment] 2018-08-28 06:40
Note that we changed the ass for the world order clip so it works now, but I can link you to an older version from git if you'd like.

**Comment by Yay295** [comment] 2018-08-29 00:35
I doubt this fixed it, but I just added code that *should* allow embedded fonts to work, like in that Momo Kyun Sword video.

**Comment by AxelTerizaki** [comment] 2018-08-29 06:57
MOmo kyun sword worked fine, actually : it's World Order - Have a nice day which didn't, and the bug still seems to be there.

I reverted the .ass file for world order (as we had found a workaround) so you can see for yourself : 

https://live.karaokes.moe/?video=%20MV%20-JAP%20-%20WORLD%20ORDER%20

If you play this one, and try to get a new random video, no subs are displayed anymore, on any video. Hit F5 and subs will display again on that video.

**Closed** 2018-08-29 18:25 UTC

**Comment by Yay295** [comment] 2018-08-29 20:17
Also I just fixed the Momo Kyun Sword font decoding.

**Comment by AxelTerizaki** [comment] 2018-08-31 08:38
We just found another case of "this breaks subtitles for every video after" : https://live.karaokes.moe/?video=%20GAME%20Opening%20-JAP%20-%20World%20of%20Final%20Fantasy%20

I've yet to find out which causes it in this particular ASS file, but there it is : 

http://mugen.karaokes.moe/en/karas/d8b09d49-9ff5-4f44-b51d-af674af28768.html

**Comment by AxelTerizaki** [comment] 2018-08-31 11:35
Okay, found the culprit : the files contain some characters that are wrongly uploaded and renamed so AnimeOpenings won't find them.

However, it seems that if a subfile is not loadable (as it is the case here, file not found) it breaks subtitle loading for future videos until the page is refreshed.

**Comment by Yay295** [comment] 2018-08-31 21:27
https://github.com/AniDevTwitter/animeopenings/commit/a0d66b9c6b7a4787188d7a4c55c4c0d7ca94ba4d should fix that. The subtitle code doesn't have any way to signal that it failed to get the file, but it shouldn't crash now.
